const $=s=>document.querySelector(s), days=$('#days'); let visible=14, active;
const pad=n=>String(n).padStart(2,'0');
function workDate(d=new Date()){let x=new Date(d);if(x.getHours()<4)x.setDate(x.getDate()-1);return `${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`}
function shift(key,n){let d=new Date(key+'T12:00:00');d.setDate(d.getDate()+n);return workDate(d)}
function label(key){let d=new Date(key+'T12:00:00'),w='일월화수목금토'[d.getDay()];return `${key} ${w}요일`}
function get(k){try{return JSON.parse(localStorage.getItem('tasks:'+k)||'[]')}catch{return []}}
function put(k,v){localStorage.setItem('tasks:'+k,JSON.stringify(v))}
function rollover(){const t=workDate(), prev=shift(t,-1), flag='rolled:'+t;if(localStorage.getItem(flag))return;let target=get(t), seen=new Set(target.map(x=>x.origin||x.id));get(prev).filter(x=>x.status==='pending').forEach(x=>{let origin=x.origin||x.id;if(!seen.has(origin))target.push({id:crypto.randomUUID(),origin,text:x.text,status:'pending'})});put(t,target);localStorage.setItem(flag,'1')}
function render(){days.innerHTML='';const t=workDate();for(let i=visible-1;i>=0;i--)days.append(makeDay(shift(t,-i)));active=t}
function makeDay(k){let s=document.createElement('section');s.className='sheet';s.dataset.date=k;s.innerHTML=`<div class="brand"><div class="logo">◆ WONTECH <small>원테크</small></div><div class="date">DATE ${label(k)}</div></div><div class="head"><div>NO</div><div>업 무 내 용</div><div>진행상황</div></div><div class="list"></div><div class="footer-actions"><button>＋ 업무 추가</button></div>`;let list=s.querySelector('.list'),arr=get(k);if(!arr.length)list.innerHTML='<div class="empty">등록된 업무가 없습니다.</div>';arr.forEach((x,i)=>list.append(row(k,x,i)));s.querySelector('.footer-actions button').onclick=()=>addTask(k);s.onclick=()=>active=k;return s}
function row(k,x,i){let r=document.createElement('div');r.className='task '+(x.status==='done'?'done':x.status==='pending'?'pending':'');r.innerHTML=`<div class="num">${i+1}</div><input class="text" value="${esc(x.text)}" placeholder="업무 내용을 입력하세요"><select class="status"><option value="">선택</option><option value="done" ${x.status==='done'?'selected':''}>완료</option><option value="pending" ${x.status==='pending'?'selected':''}>미처리</option></select><button class="remove">×</button>`;r.querySelector('.text').oninput=e=>update(k,x.id,{text:e.target.value});r.querySelector('.status').onchange=e=>{update(k,x.id,{status:e.target.value});render();go(k)};r.querySelector('.remove').onclick=e=>{e.stopPropagation();put(k,get(k).filter(v=>v.id!==x.id));render();go(k)};return r}
function esc(v=''){return v.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
function update(k,id,p){put(k,get(k).map(x=>x.id===id?{...x,...p}:x))}
function addTask(k=active||workDate()){let a=get(k);a.push({id:crypto.randomUUID(),text:'',status:''});put(k,a);render();go(k);setTimeout(()=>document.querySelector(`[data-date="${k}"] .task:last-child .text`)?.focus(),100)}
function go(k){setTimeout(()=>document.querySelector(`[data-date="${k}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}),10)}
async function only(fn){let s=document.querySelector(`[data-date="${active||workDate()}"]`);s.classList.add('printing');await fn('WONTECH_업무메모_'+(active||workDate()));s.classList.remove('printing')}
rollover();render();go(workDate());$('#today').onclick=()=>go(workDate());$('#add').onclick=()=>addTask(workDate());$('#older').onclick=()=>{visible+=14;render();go(shift(workDate(),-(visible-14)))};$('#top').onchange=e=>window.desk.top(e.target.checked);$('#jpg').onclick=()=>only(window.desk.jpg);$('#pdf').onclick=()=>only(window.desk.pdf);$('#print').onclick=()=>only(window.desk.print);
